### ISSUE TITLE
Is the SOC expressed  with the z-axis as quantization axis?

### ISSUE THREAD

**Issue by hetian-chen** [qqgu/Wannier_Add_onsite_SOC#1]
I want to calculate the MCA of some systems. So do I need to get the Hmn(R) with arbitrary spin quantization?  Thank you very much.

**Comment by qqgu** [comment]
Hi,

The code is to add the soc term to the non-soc DFT2wannier TB, and  thus there is no spin degree in the original wannierTB.  When i add the soc term, i choose the spin quantization to be z-axis, global of course.  But unlike the colinear or non-colinear calculations in DFT code, here i didnot make such constrain on electronic orbitals.  

As for MCA, wha's the meaning of the abbreviation  MCA?  it seems i am not familiar with this and can not give you any suggestion.

Hope this can help you.

**Comment by hetian-chen** [comment]
> Hi,
> 
> The code is to add the soc term to the non-soc DFT2wannier TB, and thus there is no spin degree in the original wannierTB. When i add the soc term, i choose the spin quantization to be z-axis, global of course. But unlike the colinear or non-colinear calculations in DFT code, here i didnot make such constrain on electronic orbitals.
> 
> As for MCA, wha's the meaning of the abbreviation MCA? it seems i am not familiar with this and can not give you any suggestion.
> 
> Hope this can help you.

MCA means magnetic-crystalline anisotropy, in which the exchange splitting and SOC need to be considered. This code helps me a lot. Thank you very much!

**Comment by qqgu** [comment]
Nice to  know, and glad to hear that the code helps.
