### ISSUE TITLE
Does the negative spin-orbit coupling parameter make sense?

### ISSUE THREAD

**Issue by hetian-chen** [qqgu/Wannier_Add_onsite_SOC#2]
If we express the  Hamiltonian as H = lambda L S. It seems that the lambda should be positive for less-than-half-filled shells, while is negative for more-than-half-filled shells. But it seems that lambda is all positive in tight-binding model.

**Comment by qqgu** [comment]
tight-binding model is singe-particle Hamiltonian model. the lambda is always positive. as you mentioned for less-than-half-filled ions or more-than-half-filled ions, the lambda you are talking about is a many-body effective SOC parameter. For details please the book:
_Lecture Notes on Electron Correlation and Magnetism._
![image](https://user-images.githubusercontent.com/20830366/148352907-8ea42a2d-6742-48ac-9d7e-99ecbbea0b1a.png)

**Comment by hetian-chen** [comment]
@qqgu Thank you very much
